apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-dashboard
  template:
    metadata:
      labels:
        app: k8s-dashboard
    spec:
      serviceAccount: user-dashboard
      containers:
        - name: k8s-dashboard
          image: kubedevio/k8s-dashboard
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.5"
            requests:
              memory: "64Mi"
              cpu: "0.3"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
